baseurl = "https://permitted-co.netlify.com/"
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
theme = "permitted-theme"
title = "Permitted"
[params]
custom_css = []
custom_js = []
description = "Automate your building permits. Fill in one easy-to-use forms, and we complete all the permit applications for you. For architects, engineers, contractors, commercial property managers"
disablefonts = false
favicon = "favicon.ico"
name = "Permitted.co"
[params.about]
enable = false
endpoint = "Be part<br>of our<br>story!"
subtitle = "Lorem ipsum dolor sit amet consectetur."
title = "About"
[[params.about.events]]
date = "2009-2011"
description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"
img = "1.jpg"
title = "Our Humble Beginnings"
[[params.about.events]]
date = "March 2011"
description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"
img = "2.jpg"
title = "An Agency is Born"
[[params.about.events]]
date = "December 2012"
description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"
img = "3.jpg"
title = "Our Humble Beginnings"
[[params.about.events]]
date = "July 2014"
description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"
img = "4.jpg"
title = "Phase Two Expansion"
[params.clients_list]
enable = false
[params.contact]
buttontext = "Send"
email = "info@permitted.co"
enable = true
subtitle = "Get in touch for early access and for partner opporunities"
title = "Contact us"
[params.contact.form.email]
text = "Your Email *"
warning = "Please enter your email address."
[params.contact.form.message]
text = "Your Message *"
warning = "Please enter a message."
[params.contact.form.name]
text = "Your Name *"
warning = "Please enter your name."
[params.contact.form.phone]
text = "Your Phone *"
warning = "Please enter your phone number."
[params.error404]
heading = "Page couldn't be found"
text = "Please visit [this page](/)"
[params.footer]
copyright = "Copyright 2017 GetPermitted, Inc"
enable = true
[[params.footer.social]]
icon = "fa-twitter"
link = "https://twitter.com/permittedco"
[params.hero]
buttontext = "Contact Us"
subtitle = "Speed-Up Your Building Project. Automate Your Permits."
title = "One form to get permitting requirements and pull building permits, nationwide."
[params.navigation]
brand = "Permitted"
contact = "Contact"
logo = "logo.svg"
name = "External link"
services = "Features"
team = "Team"
url = "http://gohugo.io"
weight = 10
[params.portfolio]
enable = false
subtitle = "Lorem ipsum dolor sit amet consectetur."
title = "Portfolio"
[params.portfolio.modal]
buttontext = "Close project"
category = "Category"
client = "Client"
date = "Date"
[params.services]
enable = true
subtitle = "A new way to pull building permits, coming soon."
title = "Features"
[[params.services.row]]
[[params.services.row.list]]
description = "We determine what permits you need for your project, and the authorities you need to file with"
icon = "/uploads/2017/10/29/requirements.svg"
title = "Requirements"
url = "#"
[[params.services.row.list]]
description = "Your one place to manage inspection schedules, permit renewals and other permit workflow."
icon = "fa-file-text-o"
title = "Application Forms"
url = "#"
[[params.services.row.list]]
description = "Your one place to manage inspection schedules, permit renewals and other permit workflow."
icon = "fa-building-o"
title = "Permits"
url = "#"
[params.team]
enable = true
subtitle = "We build great teams and products to solve massive problems for our customers. Get in touch if that sounds like your jam."
title = "Our amazing team"
[[params.team.members]]
bio = "Tela founded Permitted to make building permitting easier. He brings deep experience in compliance, SaaS and marketing is combined with his background in architecture and landscape architecture."
img = "tela.jpg"
name = "Tela Andrews"
position = "CEO"
social = [["fa-twitter", "https://twitter.com/the_tela"], ["fa-linkedin", "https://www.linkedin.com/in/telaandrews"]]
[[params.team.members]]
bio = "Ramin loves building technology to solve large scale problems. A veteran of Stock Twits, Tune, and fomer CTO at StockX."
img = "ramin.jpg"
name = "Ramin Keene"
position = "Development"
social = [["fa-twitter", "https://twitter.com/rmn"], ["fa-linkedin", "https://www.linkedin.com/in/raminkeene"]]
[[params.team.members]]
bio = "Derric drives branding, design and user experience. Derric has worked at Moz and Funko, and loves designing for SaaS and physical products."
img = "derric.jpg"
name = "Derric Wise"
position = "Design"
social = [["fa-twitter", "https://twitter.com/derricwise"], ["fa-linkedin", "https://www.linkedin.com/in/derricwise/"]]
[[params.team.members]]
bio = "Bonnie is passionate about operating and scaling businesses, from people to finance and legal. Bonnie brings deep experience growing compliance SaaS businesses."
img = "bonnie.jpg"
name = "Bonnie Page"
position = "Operations"
social = [["fa-twitter", "https://twitter.com/derricwise"], ["fa-linkedin", "https://www.linkedin.com/in/derricwise/"]]
[[params.team.members]]
bio = "Kane leads marketing efforts for Permitted. As owner of Content Harmony, a Seattle markeitng agency, Kane and his team drive marketing and traffic acquisition tactics and strategy."
img = "kane.jpg"
name = "Kane Jamison"
position = "Marketing"
social = [["fa-twitter", "https://twitter.com/derricwise"], ["fa-linkedin", "https://www.linkedin.com/in/derricwise/"]]
[[params.team.members]]
bio = "Steven leads our data science practice, developing metrics and insights that help our customers make sense of permitting for their projects."
img = "1.jpg"
name = "Steven Blaha"
position = "Data Science"
social = [["fa-twitter", "https://twitter.com/derricwise"], ["fa-linkedin", "https://www.linkedin.com/in/derricwise/"]]
[[params.clients]]
link = "#"
logo = "envato.jpg"
[[params.clients]]
link = "#"
logo = "designmodo.jpg"
[[params.clients]]
link = "#"
logo = "themeforest.jpg"
[[params.clients]]
link = "#"
logo = "creative-market.jpg"
